# Spring
spring:

 # Datasource
 datasource:
  driver-class-name: org.postgresql.Driver
  jdbcUrl: ${JDBC_DATABASE_URL}

 # Data
 data:
  jpa:
    repositories:
      enabled: true


 jpa:
   database: postgresql
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true

# Server
server:
  port: 8026

# Jwt
jwt:
  secretKey: secret
  expiration: 32

# Cors for admin ui
admin-ui-url: http://localhost:4200